version: '2'

services:

  broadsea-shiny:
    build: .
    image: ohdsi/broadsea-shiny
    ports:
      - "80:3838"
    volumes:
      - ./ShinyDeploy/:/srv/shiny-server/:ro
    environment:
      - shinydbServer=${shinydbServer}
      - shinydbDatabase=${shinydbDatabase}
      - shinydbPort=${shinydbPort}
      - shinydbUser=${shinydbUser}
      - shinydbPw=${shinydbPw}
      - shinydbSchema=${shinydbSchema}

